# Generated by Django 5.0.3 on 2025-04-06 13:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roles', '0002_remove_user_is_superadmin_user_phone_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Annee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annee', models.CharField(max_length=9)),
            ],
            options={
                'db_table': 'annees',
            },
        ),
        migrations.CreateModel(
            name='Filiere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_filiere', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'filieres',
            },
        ),
        migrations.CreateModel(
            name='Niveau',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_niveau', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'niveaux',
            },
        ),
        migrations.CreateModel(
            name='Semestre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_semestre', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'semestres',
            },
        ),
        migrations.AlterField(
            model_name='invitation',
            name='role',
            field=models.CharField(choices=[('etudiant', 'Etudiant'), ('enseignant', 'Enseignant'), ('admin', 'Admin'), ('superadmin', 'Superadmin')], max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('etudiant', 'Etudiant'), ('enseignant', 'Enseignant'), ('admin', 'Admin'), ('superadmin', 'Superadmin')], max_length=20),
        ),
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='admin_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'admins',
            },
        ),
        migrations.CreateModel(
            name='AdminAnnee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin', models.ForeignKey(db_column='id_admin', on_delete=django.db.models.deletion.CASCADE, to='roles.admin')),
                ('annee', models.ForeignKey(db_column='id_annee', on_delete=django.db.models.deletion.CASCADE, to='roles.annee')),
            ],
            options={
                'db_table': 'admins_annees',
                'unique_together': {('admin', 'annee')},
            },
        ),
        migrations.AddField(
            model_name='admin',
            name='annees',
            field=models.ManyToManyField(through='roles.AdminAnnee', to='roles.annee'),
        ),
        migrations.CreateModel(
            name='Enseignant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='enseignant_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'enseignants',
            },
        ),
        migrations.CreateModel(
            name='EnseignantAnnee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annee', models.ForeignKey(db_column='id_annee', on_delete=django.db.models.deletion.CASCADE, to='roles.annee')),
                ('enseignant', models.ForeignKey(db_column='id_enseignant', on_delete=django.db.models.deletion.CASCADE, to='roles.enseignant')),
            ],
            options={
                'db_table': 'enseignants_annees',
                'unique_together': {('enseignant', 'annee')},
            },
        ),
        migrations.AddField(
            model_name='enseignant',
            name='annees',
            field=models.ManyToManyField(through='roles.EnseignantAnnee', to='roles.annee'),
        ),
        migrations.CreateModel(
            name='Etudiant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='etudiant_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'etudiants',
            },
        ),
        migrations.CreateModel(
            name='EtudiantAnnee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annee', models.ForeignKey(db_column='id_annee', on_delete=django.db.models.deletion.CASCADE, to='roles.annee')),
                ('etudiant', models.ForeignKey(db_column='id_etudiant', on_delete=django.db.models.deletion.CASCADE, to='roles.etudiant')),
            ],
            options={
                'db_table': 'etudiants_annees',
                'unique_together': {('etudiant', 'annee')},
            },
        ),
        migrations.AddField(
            model_name='etudiant',
            name='annees',
            field=models.ManyToManyField(through='roles.EtudiantAnnee', to='roles.annee'),
        ),
        migrations.AddField(
            model_name='etudiant',
            name='filiere',
            field=models.ForeignKey(db_column='id_filiere', null=True, on_delete=django.db.models.deletion.CASCADE, to='roles.filiere'),
        ),
        migrations.CreateModel(
            name='EnseignantFiliere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enseignant', models.ForeignKey(db_column='id_enseignant', on_delete=django.db.models.deletion.CASCADE, to='roles.enseignant')),
                ('filiere', models.ForeignKey(db_column='id_filiere', on_delete=django.db.models.deletion.CASCADE, to='roles.filiere')),
            ],
            options={
                'db_table': 'enseignants_filieres',
                'unique_together': {('enseignant', 'filiere')},
            },
        ),
        migrations.AddField(
            model_name='enseignant',
            name='filieres',
            field=models.ManyToManyField(through='roles.EnseignantFiliere', to='roles.filiere'),
        ),
        migrations.CreateModel(
            name='AdminFiliere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin', models.ForeignKey(db_column='id_admin', on_delete=django.db.models.deletion.CASCADE, to='roles.admin')),
                ('filiere', models.ForeignKey(db_column='id_filiere', on_delete=django.db.models.deletion.CASCADE, to='roles.filiere')),
            ],
            options={
                'db_table': 'admins_filieres',
                'unique_together': {('admin', 'filiere')},
            },
        ),
        migrations.AddField(
            model_name='admin',
            name='filieres',
            field=models.ManyToManyField(through='roles.AdminFiliere', to='roles.filiere'),
        ),
        migrations.CreateModel(
            name='Matiere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_matiere', models.CharField(max_length=100)),
                ('course_code', models.CharField(db_column='courseCode', max_length=52, unique=True)),
                ('filiere', models.ForeignKey(db_column='id_filiere', null=True, on_delete=django.db.models.deletion.CASCADE, to='roles.filiere')),
                ('niveau', models.ForeignKey(db_column='id_niveau', null=True, on_delete=django.db.models.deletion.CASCADE, to='roles.niveau')),
                ('semestre', models.ForeignKey(db_column='id_semestre', null=True, on_delete=django.db.models.deletion.CASCADE, to='roles.semestre')),
            ],
            options={
                'db_table': 'matieres',
            },
        ),
        migrations.CreateModel(
            name='EnseignantMatiere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enseignant', models.ForeignKey(db_column='id_enseignant', on_delete=django.db.models.deletion.CASCADE, to='roles.enseignant')),
                ('matiere', models.ForeignKey(db_column='id_matiere', on_delete=django.db.models.deletion.CASCADE, to='roles.matiere')),
            ],
            options={
                'db_table': 'enseignants_matieres',
                'unique_together': {('enseignant', 'matiere')},
            },
        ),
        migrations.AddField(
            model_name='enseignant',
            name='matieres',
            field=models.ManyToManyField(through='roles.EnseignantMatiere', to='roles.matiere'),
        ),
        migrations.CreateModel(
            name='MatiereCommune',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_matiere_commune', models.CharField(max_length=100)),
                ('course_code', models.CharField(db_column='courseCode', max_length=52, unique=True)),
                ('filiere', models.ForeignKey(db_column='id_filiere', null=True, on_delete=django.db.models.deletion.CASCADE, to='roles.filiere')),
                ('niveau', models.ForeignKey(db_column='id_niveau', null=True, on_delete=django.db.models.deletion.CASCADE, to='roles.niveau')),
                ('semestre', models.ForeignKey(db_column='id_semestre', null=True, on_delete=django.db.models.deletion.CASCADE, to='roles.semestre')),
            ],
            options={
                'db_table': 'matieres_communes',
            },
        ),
        migrations.CreateModel(
            name='EnseignantMatiereCommune',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enseignant', models.ForeignKey(db_column='id_enseignant', on_delete=django.db.models.deletion.CASCADE, to='roles.enseignant')),
                ('matiere_commune', models.ForeignKey(db_column='id_matiere_commune', on_delete=django.db.models.deletion.CASCADE, to='roles.matierecommune')),
            ],
            options={
                'db_table': 'enseignants_matieres_communes',
                'unique_together': {('enseignant', 'matiere_commune')},
            },
        ),
        migrations.AddField(
            model_name='enseignant',
            name='matieres_communes',
            field=models.ManyToManyField(through='roles.EnseignantMatiereCommune', to='roles.matierecommune'),
        ),
        migrations.CreateModel(
            name='MatiereCommuneEtudiant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('etudiant', models.ForeignKey(db_column='id_etudiant', on_delete=django.db.models.deletion.CASCADE, to='roles.etudiant')),
                ('matiere_commune', models.ForeignKey(db_column='id_matiere_commune', on_delete=django.db.models.deletion.CASCADE, to='roles.matierecommune')),
            ],
            options={
                'db_table': 'matieres_communes_etudiants',
                'unique_together': {('etudiant', 'matiere_commune')},
            },
        ),
        migrations.AddField(
            model_name='etudiant',
            name='matieres_communes',
            field=models.ManyToManyField(through='roles.MatiereCommuneEtudiant', to='roles.matierecommune'),
        ),
        migrations.CreateModel(
            name='MatiereEtudiant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('etudiant', models.ForeignKey(db_column='id_etudiant', on_delete=django.db.models.deletion.CASCADE, to='roles.etudiant')),
                ('matiere', models.ForeignKey(db_column='id_matiere', on_delete=django.db.models.deletion.CASCADE, to='roles.matiere')),
            ],
            options={
                'db_table': 'matieres_etudiants',
                'unique_together': {('etudiant', 'matiere')},
            },
        ),
        migrations.AddField(
            model_name='etudiant',
            name='matieres',
            field=models.ManyToManyField(through='roles.MatiereEtudiant', to='roles.matiere'),
        ),
        migrations.AddField(
            model_name='etudiant',
            name='niveau',
            field=models.ForeignKey(db_column='id_niveau', null=True, on_delete=django.db.models.deletion.CASCADE, to='roles.niveau'),
        ),
        migrations.CreateModel(
            name='EnseignantNiveau',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enseignant', models.ForeignKey(db_column='id_enseignant', on_delete=django.db.models.deletion.CASCADE, to='roles.enseignant')),
                ('niveau', models.ForeignKey(db_column='id_niveau', on_delete=django.db.models.deletion.CASCADE, to='roles.niveau')),
            ],
            options={
                'db_table': 'enseignants_niveaux',
                'unique_together': {('enseignant', 'niveau')},
            },
        ),
        migrations.AddField(
            model_name='enseignant',
            name='niveaux',
            field=models.ManyToManyField(through='roles.EnseignantNiveau', to='roles.niveau'),
        ),
        migrations.CreateModel(
            name='EtudiantSemestre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('etudiant', models.ForeignKey(db_column='id_etudiant', on_delete=django.db.models.deletion.CASCADE, to='roles.etudiant')),
                ('semestre', models.ForeignKey(db_column='id_semestre', on_delete=django.db.models.deletion.CASCADE, to='roles.semestre')),
            ],
            options={
                'db_table': 'etudiants_semestres',
                'unique_together': {('etudiant', 'semestre')},
            },
        ),
        migrations.AddField(
            model_name='etudiant',
            name='semestres',
            field=models.ManyToManyField(through='roles.EtudiantSemestre', to='roles.semestre'),
        ),
        migrations.CreateModel(
            name='EnseignantSemestre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enseignant', models.ForeignKey(db_column='id_enseignant', on_delete=django.db.models.deletion.CASCADE, to='roles.enseignant')),
                ('semestre', models.ForeignKey(db_column='id_semestre', on_delete=django.db.models.deletion.CASCADE, to='roles.semestre')),
            ],
            options={
                'db_table': 'enseignants_semestres',
                'unique_together': {('enseignant', 'semestre')},
            },
        ),
        migrations.AddField(
            model_name='enseignant',
            name='semestres',
            field=models.ManyToManyField(through='roles.EnseignantSemestre', to='roles.semestre'),
        ),
        migrations.CreateModel(
            name='AdminSemestre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin', models.ForeignKey(db_column='id_admin', on_delete=django.db.models.deletion.CASCADE, to='roles.admin')),
                ('semestre', models.ForeignKey(db_column='id_semestre', on_delete=django.db.models.deletion.CASCADE, to='roles.semestre')),
            ],
            options={
                'db_table': 'admins_semestres',
                'unique_together': {('admin', 'semestre')},
            },
        ),
        migrations.AddField(
            model_name='admin',
            name='semestres',
            field=models.ManyToManyField(through='roles.AdminSemestre', to='roles.semestre'),
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cc_note', models.FloatField()),
                ('normal_note', models.FloatField()),
                ('note_final', models.FloatField()),
                ('annee', models.ForeignKey(db_column='id_annee', null=True, on_delete=django.db.models.deletion.CASCADE, to='roles.annee')),
                ('etudiant', models.ForeignKey(db_column='id_etudiant', on_delete=django.db.models.deletion.CASCADE, to='roles.etudiant')),
                ('matiere', models.ForeignKey(db_column='id_matiere', null=True, on_delete=django.db.models.deletion.CASCADE, to='roles.matiere')),
                ('matiere_commune', models.ForeignKey(db_column='id_matiere_commune', null=True, on_delete=django.db.models.deletion.CASCADE, to='roles.matierecommune')),
            ],
            options={
                'db_table': 'notes',
                'unique_together': {('etudiant', 'matiere', 'matiere_commune', 'annee')},
            },
        ),
    ]
