# Generated by Django 5.0.3 on 2025-04-06 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roles', '0003_annee_filiere_niveau_semestre_alter_invitation_role_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etudiant',
            name='matieres',
            field=models.ManyToManyField(related_name='etudiants', through='roles.MatiereEtudiant', to='roles.matiere'),
        ),
    ]
