# Generated by Django 5.0.3 on 2025-04-16 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roles', '0005_remove_admin_annees_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitation',
            name='pin',
            field=models.CharField(max_length=36, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='profileetudiant',
            unique_together={('etudiant', 'annee')},
        ),
    ]
