# Generated by Django 5.0.3 on 2025-04-28 06:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roles', '0007_alter_user_options_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='note',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='annee',
            name='annee',
            field=models.CharField(blank=True, max_length=9, null=True),
        ),
        migrations.AlterField(
            model_name='enseignantannee',
            name='annee',
            field=models.ForeignKey(blank=True, db_column='id_annee', null=True, on_delete=django.db.models.deletion.CASCADE, to='roles.annee'),
        ),
        migrations.AlterField(
            model_name='etudiantannee',
            name='annee',
            field=models.ForeignKey(blank=True, db_column='id_annee', null=True, on_delete=django.db.models.deletion.CASCADE, to='roles.annee'),
        ),
        migrations.AlterField(
            model_name='matierecommuneetudiant',
            name='annee',
            field=models.ForeignKey(blank=True, db_column='id_annee', null=True, on_delete=django.db.models.deletion.CASCADE, to='roles.annee'),
        ),
        migrations.AlterField(
            model_name='matiereetudiant',
            name='annee',
            field=models.ForeignKey(blank=True, db_column='id_annee', null=True, on_delete=django.db.models.deletion.CASCADE, to='roles.annee'),
        ),
        migrations.AlterField(
            model_name='note',
            name='annee',
            field=models.ForeignKey(blank=True, db_column='id_annee', null=True, on_delete=django.db.models.deletion.CASCADE, to='roles.annee'),
        ),
        migrations.AlterField(
            model_name='note',
            name='matiere',
            field=models.ForeignKey(blank=True, db_column='id_matiere', null=True, on_delete=django.db.models.deletion.CASCADE, to='roles.matiere'),
        ),
        migrations.AlterField(
            model_name='note',
            name='matiere_commune',
            field=models.ForeignKey(blank=True, db_column='id_matiere_commune', null=True, on_delete=django.db.models.deletion.CASCADE, to='roles.matierecommune'),
        ),
        migrations.AlterField(
            model_name='profileenseignant',
            name='annee',
            field=models.ForeignKey(blank=True, db_column='id_annee', null=True, on_delete=django.db.models.deletion.CASCADE, to='roles.annee'),
        ),
        migrations.AlterField(
            model_name='profileenseignant',
            name='matiere',
            field=models.ForeignKey(blank=True, db_column='id_matiere', null=True, on_delete=django.db.models.deletion.CASCADE, to='roles.matiere'),
        ),
        migrations.AlterField(
            model_name='profileenseignant',
            name='matiere_commune',
            field=models.ForeignKey(blank=True, db_column='id_matiere_commune', null=True, on_delete=django.db.models.deletion.CASCADE, to='roles.matierecommune'),
        ),
        migrations.AlterField(
            model_name='profileetudiant',
            name='annee',
            field=models.ForeignKey(blank=True, db_column='id_annee', null=True, on_delete=django.db.models.deletion.CASCADE, to='roles.annee'),
        ),
        migrations.AlterField(
            model_name='profileetudiant',
            name='matiere_commune',
            field=models.ForeignKey(blank=True, db_column='id_matiere_commune', null=True, on_delete=django.db.models.deletion.CASCADE, to='roles.matierecommune'),
        ),
        migrations.AlterUniqueTogether(
            name='note',
            unique_together={('etudiant', 'matiere', 'annee')},
        ),
    ]
