# Generated by Django 5.0.3 on 2025-05-02 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('roles', '0008_alter_note_unique_together_alter_annee_annee_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='phone_number',
        ),
    ]
