# Generated by Django 5.0.3 on 2025-05-11 21:49

import django.db.models.deletion
import roles.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roles', '0009_remove_user_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annee',
            name='annee',
            field=models.CharField(max_length=9, unique=True),
        ),
        migrations.AlterField(
            model_name='etudiantannee',
            name='annee',
            field=models.ForeignKey(db_column='id_annee', default=roles.models.get_default_annee, on_delete=django.db.models.deletion.CASCADE, to='roles.annee'),
        ),
        migrations.AlterField(
            model_name='profileetudiant',
            name='annee',
            field=models.ForeignKey(db_column='id_annee', default=roles.models.get_default_annee, on_delete=django.db.models.deletion.CASCADE, to='roles.annee'),
        ),
    ]
