# Generated by Django 5.0.3 on 2025-05-11 21:51

import django.db.models.deletion
import roles.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roles', '0010_alter_annee_annee_alter_etudiantannee_annee_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etudiantannee',
            name='annee',
            field=models.ForeignKey(db_column='id_annee', default=roles.models.get_default_annee, on_delete=django.db.models.deletion.CASCADE, to='roles.annee'),
        ),
    ]
