# Generated by Django 5.0.3 on 2025-05-13 20:32

import django.db.models.deletion
import roles.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roles', '0011_alter_etudiantannee_annee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etudiantannee',
            name='annee',
            field=models.ForeignKey(db_column='id_annee', default=roles.models.get_default_annee, on_delete=django.db.models.deletion.CASCADE, to='roles.annee'),
        ),
    ]
