# Generated by Django 5.0.3 on 2025-05-18 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roles', '0012_alter_etudiantannee_annee'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='matiere',
            index=models.Index(fields=['filiere', 'semestre', 'niveau'], name='matieres_id_fili_8bb096_idx'),
        ),
        migrations.AddIndex(
            model_name='matierecommune',
            index=models.Index(fields=['filiere', 'semestre', 'niveau'], name='matieres_co_id_fili_dbd2c3_idx'),
        ),
    ]
