# Generated by Django 5.0.3 on 2025-05-18 02:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roles', '0013_matiere_matieres_id_fili_8bb096_idx_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='note',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='profileetudiant',
            name='matiere',
        ),
        migrations.RemoveField(
            model_name='profileetudiant',
            name='matiere_commune',
        ),
        migrations.AlterField(
            model_name='etudiant',
            name='filiere',
            field=models.ForeignKey(blank=True, db_column='id_filiere', null=True, on_delete=django.db.models.deletion.SET_NULL, to='roles.filiere'),
        ),
        migrations.AlterField(
            model_name='etudiant',
            name='niveau',
            field=models.ForeignKey(blank=True, db_column='id_niveau', null=True, on_delete=django.db.models.deletion.SET_NULL, to='roles.niveau'),
        ),
        migrations.AddConstraint(
            model_name='note',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('matiere__isnull', False), ('matiere_commune__isnull', True)), models.Q(('matiere__isnull', True), ('matiere_commune__isnull', False)), _connector='OR'), name='check_matiere_or_matiere_commune'),
        ),
        migrations.AddConstraint(
            model_name='note',
            constraint=models.UniqueConstraint(condition=models.Q(('matiere__isnull', False)), fields=('etudiant', 'matiere', 'annee'), name='unique_etudiant_matiere_annee'),
        ),
        migrations.AddConstraint(
            model_name='note',
            constraint=models.UniqueConstraint(condition=models.Q(('matiere_commune__isnull', False)), fields=('etudiant', 'matiere_commune', 'annee'), name='unique_etudiant_matiere_commune_annee'),
        ),
    ]
