# Generated by Django 5.0.3 on 2025-05-18 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roles', '0014_alter_note_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matiere',
            name='course_code',
            field=models.CharField(max_length=52, unique=True),
        ),
        migrations.AlterField(
            model_name='matierecommune',
            name='course_code',
            field=models.CharField(max_length=52, unique=True),
        ),
    ]
